-- =============================================================
-- eআরণ্যক — News Article IDs and Admin Roles
-- SAFE MIGRATION
-- Preserves all existing data.
-- =============================================================


-- =============================================================
-- 1. ADD STABLE NUMERIC ARTICLE ID
-- =============================================================

ALTER TABLE public.wildlife_news
ADD COLUMN IF NOT EXISTS article_id bigint
GENERATED BY DEFAULT AS IDENTITY;


-- Backfill any existing records that somehow have NULL article_id.
UPDATE public.wildlife_news
SET article_id = DEFAULT
WHERE article_id IS NULL;


-- Ensure every article always has an ID.
ALTER TABLE public.wildlife_news
ALTER COLUMN article_id SET NOT NULL;


-- Ensure article IDs are unique.
CREATE UNIQUE INDEX IF NOT EXISTS wildlife_news_article_id_key
ON public.wildlife_news(article_id);


-- =============================================================
-- 2. ADD USER ROLE
-- =============================================================

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user';


-- Ensure only valid roles can be stored.
ALTER TABLE public.profiles
DROP CONSTRAINT IF EXISTS profiles_role_check;

ALTER TABLE public.profiles
ADD CONSTRAINT profiles_role_check
CHECK (role IN ('user', 'admin'));


-- =============================================================
-- 3. ADMIN / EDITOR CHECK
-- =============================================================

CREATE OR REPLACE FUNCTION public.is_editor()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.profiles p
    WHERE p.id = auth.uid()
      AND p.role = 'admin'
  );
$$;


-- Allow authenticated users to use the helper.
GRANT EXECUTE ON FUNCTION public.is_editor() TO authenticated;


-- =============================================================
-- 4. PROMOTE ADMIN USER
-- =============================================================

-- Replace YOUR_ADMIN_EMAIL with your actual login email.

-- UPDATE public.profiles
-- SET role = 'admin'
-- WHERE id IN (
--   SELECT id
--   FROM auth.users
--   WHERE email = 'manojitchatterjee2007@gmail.com'
-- );