-- =============================================================================
-- eআরণ্যক / eAranyak
-- Phase 5: Citizen Science / Wildlife Sightings
-- Schema + RLS + Indexes + Triggers + Public Views + Storage Bucket + RPCs
--
-- Design notes
--  * Additive & idempotent. Phase 4 (daily_wildlife_features / about_us_content),
--    the wildlife_gallery architecture and every existing content-protection
--    mechanism are left untouched.
--  * Precise coordinates live ONLY in public.wildlife_sightings, whose SELECT
--    policies exclude anon/public. Public screens read the masked projection
--    public.public_wildlife_sightings (coordinates are not columns there).
--  * Publication state is server-authoritative: a BEFORE trigger on the table
--    forces is_published = (status = 'published') and restores every editorial
--    column for non-editor writers, so the client can never bypass review.
--  * Sensitive species are masked server-side (IUCN threat categories and
--    breeding/nest/roost sites) before any public label is derived.
--  * Every state transition is written to an append-only audit log, and
--    contributor notifications are generated by the database (tamper-proof).
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. HELPER FUNCTIONS (pure / immutable — safe for views & triggers)
-- -----------------------------------------------------------------------------

-- Masking ladder: normal -> user/editor precision, elevated -> district,
-- high -> region, critical -> state only. Precise coordinates are NEVER public.
create or replace function public.effective_sighting_precision(
  p_precision text,
  p_sensitivity text
)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_sensitivity, 'normal') = 'critical' then 'hidden'
    when coalesce(p_sensitivity, 'normal') = 'high'
         and coalesce(p_precision, 'district') in ('precise_private', 'district')
      then 'region'
    when coalesce(p_precision, 'district') not in
         ('precise_private', 'district', 'region', 'hidden')
      then 'district'
    else coalesce(p_precision, 'district')
  end;
$$;

-- Bengali-first public location label built from the masked precision.
create or replace function public.build_public_location_label(
  p_district text,
  p_state text,
  p_country text,
  p_precision text,
  p_sensitivity text
)
returns text
language sql
immutable
as $$
  with parts as (
    select
      nullif(btrim(coalesce(p_district, '')), '') as district,
      nullif(btrim(coalesce(p_state, '')), '') as state,
      nullif(btrim(coalesce(p_country, '')), '') as country,
      public.effective_sighting_precision(p_precision, p_sensitivity) as precision
  )
  select case
    when (select district from parts) is null
         and (select state from parts) is null
         and (select country from parts) is null then null
    when (select precision from parts) = 'hidden'
      then coalesce((select state from parts), (select country from parts), 'ভারত')
    when (select district from parts) is null
      then coalesce((select state from parts), (select country from parts), 'ভারত')
    when (select precision from parts) = 'region'
      then (select district from parts) || '-এর কাছে, '
           || coalesce((select state from parts), (select country from parts), 'ভারত')
    else (select district from parts) || ' জেলা, '
         || coalesce((select state from parts), (select country from parts), 'ভারত')
  end;
$$;

-- Sensitivity inference from the IUCN status supplied by user/editor.
create or replace function public.infer_sighting_sensitivity(
  p_iucn text,
  p_current text
)
returns text
language sql
immutable
as $$
  select case
    when coalesce(p_current, 'normal') = 'critical' then 'critical'
    when lower(btrim(coalesce(p_iucn, ''))) in
         ('cr', 'en', 'vu', 'nt', 'critically endangered', 'endangered',
          'vulnerable', 'near threatened') then 'high'
    when coalesce(p_current, 'normal') = 'high' then 'high'
    when coalesce(p_current, 'normal') = 'elevated' then 'elevated'
    else 'normal'
  end;
$$;

-- Duplicate / near-duplicate fingerprint (species + day + place).
create or replace function public.build_sighting_content_hash(
  p_common_name text,
  p_bengali_name text,
  p_scientific_name text,
  p_observed_at date,
  p_district text
)
returns text
language sql
immutable
as $$
  select md5(
    lower(btrim(coalesce(p_scientific_name, ''))) || '|' ||
    lower(btrim(coalesce(p_common_name, ''))) || '|' ||
    lower(btrim(coalesce(p_bengali_name, ''))) || '|' ||
    coalesce(p_observed_at::text, '') || '|' ||
    lower(btrim(coalesce(p_district, '')))
  );
$$;

-- -----------------------------------------------------------------------------
-- 2. TABLES
-- -----------------------------------------------------------------------------

create table if not exists public.wildlife_sightings (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,

  -- lifecycle
  status text not null default 'draft'
    check (status in ('draft', 'submitted', 'under_review', 'needs_information',
                      'approved', 'published', 'rejected', 'archived')),
  submitted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- species (user identification; editorial verification is a separate field)
  common_name text not null,
  bengali_name text,
  scientific_name text,
  description text,             -- Bengali observation description
  observation_notes text,
  iucn_status text,

  -- observation
  observed_at date not null default current_date,
  observed_time text,           -- approximate time, free text
  habitat text,
  individual_count integer
    check (individual_count is null or individual_count >= 0),
  behaviour text,

  -- location (precise coordinates stay private)
  district text,
  state text,
  country text default 'India',
  latitude double precision,
  longitude double precision,
  location_precision text not null default 'district'
    check (location_precision in ('precise_private', 'district', 'region', 'hidden')),
  public_location_precision text not null default 'district',
  public_location_label text,
  sensitivity_level text not null default 'normal'
    check (sensitivity_level in ('normal', 'elevated', 'high', 'critical')),
  sensitivity_source text default 'auto',
  breeding_site boolean not null default false,

  -- editorial verification
  verification_status text not null default 'user_reported'
    check (verification_status in ('unverified', 'user_reported', 'ai_suggestion',
                                   'editor_verified', 'scientifically_verified')),
  ai_suggested_species text,
  ai_suggestion_note text,
  editor_notes text,
  rejection_reason text,
  info_request_message text,

  -- publication / curation
  featured boolean not null default false,
  editorial_priority integer not null default 10,
  is_published boolean not null default false,
  published_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,

  -- contributor attribution & privacy
  contributor_display_name text,
  contributor_privacy text not null default 'named'
    check (contributor_privacy in ('named', 'anonymous')),

  -- abuse / moderation
  is_flagged boolean not null default false,
  flag_reason text,
  content_hash text,
  duplicate_of uuid references public.wildlife_sightings(id) on delete set null,
  submission_source text default 'app'
);

comment on table public.wildlife_sightings is
  'Phase 5 citizen-science wildlife sightings. Public readers use public.public_wildlife_sightings (masked projection); precise coordinates are never exposed publicly.';

create table if not exists public.wildlife_sighting_media (
  id uuid primary key default gen_random_uuid(),
  sighting_id uuid not null references public.wildlife_sightings(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  media_type text not null default 'photo'
    check (media_type in ('photo', 'audio', 'video')),
  bucket_id text not null default 'citizen_sightings',
  storage_path text not null,
  mime_type text,
  file_size_bytes bigint,
  caption text,
  display_order integer not null default 0,
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.wildlife_sighting_audit_log (
  id uuid primary key default gen_random_uuid(),
  sighting_id uuid references public.wildlife_sightings(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  actor_role text,
  action text not null,
  from_status text,
  to_status text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.sighting_notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  sighting_id uuid references public.wildlife_sightings(id) on delete cascade,
  kind text not null
    check (kind in ('submission_received', 'info_requested', 'approved',
                    'published', 'rejected', 'archived', 'editor_note', 'flagged')),
  title_bn text not null,
  body_bn text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.wildlife_contributor_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  privacy text not null default 'named' check (privacy in ('named', 'anonymous')),
  district text,
  state text,
  bio_bn text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- 3. INDEXES
-- -----------------------------------------------------------------------------

create index if not exists wildlife_sightings_status_idx
  on public.wildlife_sightings (status, submitted_at desc);

create index if not exists wildlife_sightings_published_idx
  on public.wildlife_sightings (is_published, published_at desc);

create index if not exists wildlife_sightings_user_idx
  on public.wildlife_sightings (user_id, submitted_at desc);

create index if not exists wildlife_sightings_observed_idx
  on public.wildlife_sightings (observed_at desc);

create index if not exists wildlife_sightings_district_idx
  on public.wildlife_sightings (lower(district));

create index if not exists wildlife_sightings_state_idx
  on public.wildlife_sightings (lower(state));

create index if not exists wildlife_sightings_species_idx
  on public.wildlife_sightings (lower(common_name));

create index if not exists wildlife_sightings_bengali_idx
  on public.wildlife_sightings (lower(bengali_name));

create index if not exists wildlife_sightings_featured_idx
  on public.wildlife_sightings (featured, published_at desc)
  where is_published = true and featured = true;

create index if not exists wildlife_sightings_flagged_idx
  on public.wildlife_sightings (is_flagged, submitted_at desc)
  where is_flagged = true;

create index if not exists wildlife_sightings_hash_idx
  on public.wildlife_sightings (content_hash);

create index if not exists wildlife_sighting_media_sighting_idx
  on public.wildlife_sighting_media (sighting_id, media_type, display_order);

create index if not exists wildlife_sighting_media_user_idx
  on public.wildlife_sighting_media (user_id, created_at desc);

create index if not exists wildlife_sighting_audit_sighting_idx
  on public.wildlife_sighting_audit_log (sighting_id, created_at desc);

create index if not exists sighting_notifications_user_idx
  on public.sighting_notifications (user_id, created_at desc);

create index if not exists sighting_notifications_unread_idx
  on public.sighting_notifications (user_id)
  where is_read = false;

-- -----------------------------------------------------------------------------
-- 4. TABLE GRANTS
-- New tables are not auto-exposed to the Data API; explicit grants are required.
-- RLS remains the effective gate for every row.
-- -----------------------------------------------------------------------------

grant select, insert, update, delete on public.wildlife_sightings to authenticated;
grant select, insert, update, delete on public.wildlife_sighting_media to authenticated;
grant select on public.wildlife_sighting_audit_log to authenticated;
grant select, update, delete on public.sighting_notifications to authenticated;
grant select, insert, update, delete on public.wildlife_contributor_profiles to authenticated;

-- -----------------------------------------------------------------------------
-- 5. TRIGGER FUNCTIONS
-- -----------------------------------------------------------------------------

-- Editorial guard: server-authoritative status, editorial-field protection,
-- sensitivity masking, rate limiting, publication sync and de-duplication.
create or replace function public.wildlife_sightings_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_editor boolean := public.is_editor();
  v_uid uuid := auth.uid();
  v_recent integer;
  v_last timestamptz;
begin
  if coalesce(auth.jwt() ->> 'role', '') = 'service_role'
     or coalesce(current_setting('role', true), '') = 'service_role'
     or coalesce(current_setting('earanyak.system_write', true), '') = 'on' then
    null; -- Automation / service role / vetted definer RPC is trusted.
  elsif tg_op = 'INSERT' then
    if not v_is_editor then
      if v_uid is null then
        raise exception 'লগইন আবশ্যক / Authentication required';
      end if;

      -- Abuse protection: max 20 submissions per rolling 24h, 10s minimum gap.
      select count(*) into v_recent
        from public.wildlife_sightings
       where user_id = v_uid and submitted_at > now() - interval '24 hours';
      if v_recent >= 20 then
        insert into public.wildlife_sighting_audit_log (actor_id, actor_role, action, details)
        values (v_uid, 'user', 'rate_limit_blocked',
                jsonb_build_object('window', '24h', 'count', v_recent));
        raise exception 'একদিনে অনেকগুলি জমা হয়ে গেছে — অনুগ্রহ করে পরে আবার চেষ্টা করুন। / Daily submission limit reached.';
      end if;

      select max(submitted_at) into v_last
        from public.wildlife_sightings where user_id = v_uid;
      if v_last is not null and v_last > now() - interval '10 seconds' then
        insert into public.wildlife_sighting_audit_log (actor_id, actor_role, action, details)
        values (v_uid, 'user', 'rate_limit_blocked', jsonb_build_object('window', '10s'));
        raise exception 'একটু ধীরে — কয়েক সেকেন্ড পরে আবার পাঠান। / Please try again in a few seconds.';
      end if;

      NEW.user_id := v_uid;
      NEW.sensitivity_source := 'auto';
      NEW.duplicate_of := null;
      NEW.reviewed_by := null;
      NEW.reviewed_at := null;
      NEW.editor_notes := null;
      NEW.rejection_reason := null;
      NEW.info_request_message := null;
      NEW.ai_suggested_species := null;
      NEW.ai_suggestion_note := null;
      NEW.featured := false;
      NEW.editorial_priority := 10;
      NEW.is_flagged := false;
      NEW.status := case when NEW.status in ('draft', 'submitted') then NEW.status else 'submitted' end;
    end if;
  else
    -- UPDATE
    if not v_is_editor then
      if v_uid is null or OLD.user_id is distinct from v_uid then
        raise exception 'এই রেকর্ড পরিবর্তনের অনুমতি নেই / Not permitted to modify this record';
      end if;
      if OLD.status not in ('draft', 'submitted', 'needs_information') then
        raise exception 'পর্যালোচনা শুরু হওয়ার পরে জমা আর সম্পাদনা করা যায় না / This sighting can no longer be edited';
      end if;

      NEW.user_id := OLD.user_id;
      NEW.status := case when NEW.status in ('draft', 'submitted') then NEW.status else OLD.status end;
      NEW.sensitivity_source := OLD.sensitivity_source;
      NEW.duplicate_of := OLD.duplicate_of;
      NEW.reviewed_by := OLD.reviewed_by;
      NEW.reviewed_at := OLD.reviewed_at;
      NEW.editor_notes := OLD.editor_notes;
      NEW.rejection_reason := OLD.rejection_reason;
      NEW.info_request_message := OLD.info_request_message;
      NEW.ai_suggested_species := OLD.ai_suggested_species;
      NEW.ai_suggestion_note := OLD.ai_suggestion_note;
      NEW.verification_status := OLD.verification_status;
      NEW.featured := OLD.featured;
      NEW.editorial_priority := OLD.editorial_priority;
      NEW.is_flagged := OLD.is_flagged;
      NEW.flag_reason := OLD.flag_reason;
      NEW.published_at := OLD.published_at;
      NEW.content_hash := OLD.content_hash;
    else
      NEW.user_id := coalesce(NEW.user_id, OLD.user_id);
    end if;
  end if;

  -- Normalise and validate required content.
  NEW.common_name := nullif(btrim(coalesce(NEW.common_name, '')), '');
  if NEW.common_name is null then
    raise exception 'প্রজাতির নাম আবশ্যক / Species name is required';
  end if;
  NEW.bengali_name := nullif(btrim(coalesce(NEW.bengali_name, '')), '');
  NEW.scientific_name := nullif(btrim(coalesce(NEW.scientific_name, '')), '');
  NEW.description := nullif(btrim(coalesce(NEW.description, '')), '');
  NEW.district := nullif(btrim(coalesce(NEW.district, '')), '');
  NEW.state := nullif(btrim(coalesce(NEW.state, '')), '');
  NEW.country := coalesce(nullif(btrim(coalesce(NEW.country, '')), ''), 'India');

  if NEW.observed_at is null then NEW.observed_at := current_date; end if;
  if NEW.observed_at > current_date then NEW.observed_at := current_date; end if;

  if NEW.latitude is not null and (NEW.latitude < -90 or NEW.latitude > 90) then
    raise exception 'অবৈধ অক্ষাংশ / Invalid latitude';
  end if;
  if NEW.longitude is not null and (NEW.longitude < -180 or NEW.longitude > 180) then
    raise exception 'অবৈধ দ্রাঘিমাংশ / Invalid longitude';
  end if;

  -- Sensitivity: IUCN threat categories and breeding sites auto-mask.
  if v_is_editor and NEW.sensitivity_source = 'editor' then
    null; -- editorial override respected
  else
    NEW.sensitivity_level :=
      public.infer_sighting_sensitivity(NEW.iucn_status, NEW.sensitivity_level);
  end if;
  if coalesce(NEW.breeding_site, false) then
    NEW.sensitivity_level := 'critical';
    NEW.sensitivity_source := 'breeding_site';
  end if;

  NEW.public_location_precision :=
    public.effective_sighting_precision(NEW.location_precision, NEW.sensitivity_level);

  -- Editors may override the public label; everyone else gets the masked label.
  if v_is_editor
     and nullif(btrim(coalesce(NEW.public_location_label, '')), '') is not null
     and (tg_op = 'INSERT'
          or NEW.public_location_label is distinct from OLD.public_location_label) then
    NEW.public_location_label := btrim(NEW.public_location_label);
  else
    NEW.public_location_label := public.build_public_location_label(
      NEW.district, NEW.state, NEW.country, NEW.location_precision, NEW.sensitivity_level);
  end if;

  -- Server-authoritative publication state.
  NEW.is_published := (NEW.status = 'published');
  if NEW.is_published then
    NEW.published_at := coalesce(NEW.published_at, now());
  end if;

  if tg_op = 'INSERT' then
    NEW.submitted_at := coalesce(NEW.submitted_at, now());
  else
    if NEW.status is distinct from OLD.status and v_is_editor then
      NEW.reviewed_at := now();
      NEW.reviewed_by := coalesce(v_uid, OLD.reviewed_by);
    end if;
    if NEW.status = 'submitted' and OLD.status in ('draft', 'needs_information') then
      NEW.submitted_at := now();
    end if;
  end if;

  NEW.content_hash := public.build_sighting_content_hash(
    NEW.common_name, NEW.bengali_name, NEW.scientific_name, NEW.observed_at, NEW.district);

  if NEW.duplicate_of is null and NEW.content_hash is not null then
    select s.id into NEW.duplicate_of
      from public.wildlife_sightings s
     where s.user_id is not distinct from coalesce(NEW.user_id, v_uid)
       and s.content_hash = NEW.content_hash
       and s.id is distinct from NEW.id
       and s.status <> 'rejected'
     order by s.created_at desc
     limit 1;
  end if;

  NEW.updated_at := now();
  return NEW;
end;
$$;

-- After-change: append-only audit trail, contributor notifications (written by
-- the database so they cannot be forged by clients) and media visibility sync.
create or replace function public.wildlife_sightings_after_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor uuid := auth.uid();
  v_role text := case
    when public.is_editor() then 'editor'
    when auth.uid() is null then 'system'
    else 'user' end;
  v_name text := coalesce(nullif(NEW.bengali_name, ''), nullif(NEW.common_name, ''), 'দর্শন');
  v_kind text;
  v_title text;
  v_body text;
begin
  if tg_op = 'INSERT' then
    insert into public.wildlife_sighting_audit_log
      (sighting_id, actor_id, actor_role, action, to_status, details)
    values (NEW.id, coalesce(v_actor, NEW.user_id), v_role,
            case when NEW.status = 'draft' then 'draft_created' else 'submission_received' end,
            NEW.status,
            jsonb_build_object('sensitivity', NEW.sensitivity_level,
                               'duplicate_of', NEW.duplicate_of));

    if NEW.status = 'submitted' and NEW.user_id is not null then
      insert into public.sighting_notifications (user_id, sighting_id, kind, title_bn, body_bn)
      values (NEW.user_id, NEW.id, 'submission_received',
              'আপনার দর্শন জমা হয়েছে 🌿',
              v_name || ' — সম্পাদকীয় পর্যালোচনার জন্য জমা হয়েছে। ধন্যবাদ!');
    end if;

    return null;
  end if;

  -- UPDATE branch
  if NEW.is_published is distinct from OLD.is_published then
    update public.wildlife_sighting_media
       set is_public = NEW.is_published
     where sighting_id = NEW.id;
  end if;

  if NEW.status is distinct from OLD.status then
    insert into public.wildlife_sighting_audit_log
      (sighting_id, actor_id, actor_role, action, from_status, to_status, details)
    values (NEW.id, v_actor, v_role, 'status_change', OLD.status, NEW.status,
            jsonb_build_object('featured', NEW.featured,
                               'verification_status', NEW.verification_status));

    v_kind := case NEW.status
      when 'needs_information' then 'info_requested'
      when 'approved' then 'approved'
      when 'published' then 'published'
      when 'rejected' then 'rejected'
      when 'archived' then 'archived'
      else null end;

    if v_kind is not null and NEW.user_id is not null then
      v_title := case v_kind
        when 'info_requested' then 'আপনার দর্শন সম্পর্কে কিছু তথ্য প্রয়োজন'
        when 'approved' then 'আপনার দর্শন যাচাই হয়েছে ✅'
        when 'published' then 'আপনার দর্শন প্রকাশিত হয়েছে 🌿'
        when 'rejected' then 'আপনার দর্শন প্রকাশ করা হয়নি'
        else 'আপনার দর্শন সংরক্ষণাগারে রাখা হয়েছে' end;

      v_body := case v_kind
        when 'info_requested' then coalesce(
          nullif(btrim(coalesce(NEW.info_request_message, '')), ''),
          'অনুগ্রহ করে আপনার দর্শনের বিবরণ বা ছবি সম্পূর্ণ করুন।')
        when 'approved' then v_name || ' — সম্পাদকীয় যাচাই সম্পূর্ণ হয়েছে।'
        when 'published' then v_name || ' — এখন নাগরিক বিজ্ঞান বিভাগে প্রকাশিত।'
        when 'rejected' then coalesce(
          nullif(btrim(coalesce(NEW.rejection_reason, '')), ''),
          'আপনার জমাটি এই মুহূর্তে প্রকাশের জন্য উপযুক্ত ছিল না।')
        else v_name || ' — আর্কাইভে সংরক্ষিত।' end;

      insert into public.sighting_notifications (user_id, sighting_id, kind, title_bn, body_bn)
      values (NEW.user_id, NEW.id, v_kind, v_title, v_body);
    end if;
  elsif NEW.editor_notes is distinct from OLD.editor_notes
        or NEW.verification_status is distinct from OLD.verification_status
        or NEW.featured is distinct from OLD.featured
        or NEW.public_location_label is distinct from OLD.public_location_label
        or NEW.is_flagged is distinct from OLD.is_flagged then
    insert into public.wildlife_sighting_audit_log
      (sighting_id, actor_id, actor_role, action, from_status, to_status, details)
    values (NEW.id, v_actor, v_role, 'editorial_update', OLD.status, NEW.status,
            jsonb_build_object(
              'verification_status', NEW.verification_status,
              'featured', NEW.featured,
              'public_location_label', NEW.public_location_label,
              'is_flagged', NEW.is_flagged,
              'flag_reason', NEW.flag_reason));
  end if;

  return null;
end;
$$;

-- Media guard: path-traversal safe, MIME/size validated, quota-limited.
create or replace function public.wildlife_sighting_media_guard()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_is_editor boolean := public.is_editor();
  v_uid uuid := auth.uid();
  v_sighting public.wildlife_sightings%rowtype;
  v_count integer;
  v_limit integer;
  v_max_bytes bigint;
  v_allowed_mime text[] := array[
    'image/jpeg', 'image/jpg', 'image/png', 'image/webp',
    'audio/mpeg', 'audio/mp3', 'audio/mp4', 'audio/wav', 'audio/x-wav', 'audio/ogg',
    'video/mp4', 'video/quicktime', 'video/webm'];
begin
  select * into v_sighting
    from public.wildlife_sightings s where s.id = NEW.sighting_id;

  if v_sighting.id is null then
    raise exception 'দর্শনটি পাওয়া যায়নি / Sighting not found';
  end if;

  if not v_is_editor then
    if v_uid is null or v_sighting.user_id is distinct from v_uid then
      raise exception 'অনুমতি নেই / Not permitted';
    end if;
    if v_sighting.status not in ('draft', 'submitted', 'needs_information') then
      raise exception 'পর্যালোচনার পরে ফাইল যোগ করা যায় না / Media can no longer be added';
    end if;
    NEW.user_id := v_uid;
  else
    NEW.user_id := coalesce(NEW.user_id, v_sighting.user_id);
  end if;

  NEW.media_type := lower(btrim(coalesce(NEW.media_type, 'photo')));
  if NEW.media_type not in ('photo', 'audio', 'video') then
    raise exception 'অসমর্থিত ফাইল ধরন / Unsupported media type';
  end if;

  NEW.bucket_id := coalesce(nullif(btrim(coalesce(NEW.bucket_id, '')), ''), 'citizen_sightings');
  if NEW.bucket_id <> 'citizen_sightings' then
    raise exception 'অসমর্থিত স্টোরেজ / Unsupported bucket';
  end if;

  -- Storage path must be exactly {user_id}/{sighting_id}/{safe-filename}
  NEW.storage_path := btrim(coalesce(NEW.storage_path, ''));
  if NEW.storage_path = ''
     or position('..' in NEW.storage_path) > 0
     or position('\' in NEW.storage_path) > 0
     or left(NEW.storage_path, 1) = '/'
     or position('//' in NEW.storage_path) > 0
     or NEW.storage_path !~ '^[0-9a-fA-F-]{36}/[0-9a-fA-F-]{36}/[A-Za-z0-9._-]+$' then
    raise exception 'অবৈধ ফাইল পাথ / Invalid storage path';
  end if;

  if split_part(NEW.storage_path, '/', 2) <> NEW.sighting_id::text then
    raise exception 'অবৈধ ফাইল অবস্থান / Invalid media location';
  end if;
  if split_part(NEW.storage_path, '/', 1) <> coalesce(v_sighting.user_id::text, v_uid::text) then
    raise exception 'অবৈধ ফাইল অবস্থান / Invalid media owner folder';
  end if;

  NEW.mime_type := lower(btrim(coalesce(NEW.mime_type, '')));
  if NEW.mime_type <> '' and not (NEW.mime_type = any (v_allowed_mime)) then
    raise exception 'অসমর্থিত ফাইল ফরম্যাট / Unsupported file format';
  end if;

  v_max_bytes := case NEW.media_type
    when 'photo' then 15728640      -- 15 MB
    when 'audio' then 26214400      -- 25 MB
    else 104857600 end;             -- 100 MB video
  if NEW.file_size_bytes is not null and NEW.file_size_bytes > v_max_bytes then
    raise exception 'ফাইলটি অনেক বড় / File exceeds the size limit';
  end if;

  select count(*) into v_count
    from public.wildlife_sighting_media m
   where m.sighting_id = NEW.sighting_id
     and m.media_type = NEW.media_type
     and m.id is distinct from NEW.id;
  v_limit := case NEW.media_type when 'photo' then 8 when 'audio' then 2 else 2 end;
  if v_count >= v_limit then
    raise exception 'এই দর্শনে আরও ফাইল যোগ করা যাবে না / Media limit reached';
  end if;

  NEW.caption := nullif(btrim(coalesce(NEW.caption, '')), '');
  NEW.display_order := coalesce(NEW.display_order, 0);
  NEW.is_public := (v_sighting.status = 'published' and v_sighting.is_published);
  return NEW;
end;
$$;

-- -----------------------------------------------------------------------------
-- 6. TRIGGERS
-- -----------------------------------------------------------------------------

drop trigger if exists wildlife_sightings_guard_trigger on public.wildlife_sightings;
create trigger wildlife_sightings_guard_trigger
  before insert or update on public.wildlife_sightings
  for each row execute function public.wildlife_sightings_guard();

drop trigger if exists wildlife_sightings_after_change_trigger on public.wildlife_sightings;
create trigger wildlife_sightings_after_change_trigger
  after insert or update on public.wildlife_sightings
  for each row execute function public.wildlife_sightings_after_change();

drop trigger if exists wildlife_sighting_media_guard_trigger on public.wildlife_sighting_media;
create trigger wildlife_sighting_media_guard_trigger
  before insert or update on public.wildlife_sighting_media
  for each row execute function public.wildlife_sighting_media_guard();

create or replace function public.touch_contributor_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  NEW.updated_at := now();
  return NEW;
end;
$$;

drop trigger if exists wildlife_contributor_profiles_touch on public.wildlife_contributor_profiles;
create trigger wildlife_contributor_profiles_touch
  before update on public.wildlife_contributor_profiles
  for each row execute function public.touch_contributor_profile();

-- -----------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY
-- Users own their submissions; editors own the editorial workflow; anonymous
-- readers only ever see the masked public views created in section 8.
-- -----------------------------------------------------------------------------

alter table public.wildlife_sightings enable row level security;

drop policy if exists "users insert own sightings" on public.wildlife_sightings;
create policy "users insert own sightings"
  on public.wildlife_sightings for insert to authenticated
  with check (auth.uid() = user_id and status in ('draft', 'submitted') and is_published = false);

drop policy if exists "owners and editors read sightings" on public.wildlife_sightings;
create policy "owners and editors read sightings"
  on public.wildlife_sightings for select to authenticated
  using (auth.uid() = user_id or public.is_editor());

drop policy if exists "owners update editable sightings" on public.wildlife_sightings;
create policy "owners update editable sightings"
  on public.wildlife_sightings for update to authenticated
  using (auth.uid() = user_id and status in ('draft', 'submitted', 'needs_information'))
  with check (auth.uid() = user_id and status in ('draft', 'submitted', 'needs_information'));

drop policy if exists "editors update sightings" on public.wildlife_sightings;
create policy "editors update sightings"
  on public.wildlife_sightings for update to authenticated
  using (public.is_editor())
  with check (public.is_editor());

drop policy if exists "owners delete unreviewed sightings" on public.wildlife_sightings;
create policy "owners delete unreviewed sightings"
  on public.wildlife_sightings for delete to authenticated
  using (auth.uid() = user_id and status in ('draft', 'submitted', 'needs_information', 'rejected'));

drop policy if exists "editors delete sightings" on public.wildlife_sightings;
create policy "editors delete sightings"
  on public.wildlife_sightings for delete to authenticated
  using (public.is_editor());

alter table public.wildlife_sighting_media enable row level security;

drop policy if exists "sighting media read" on public.wildlife_sighting_media;
create policy "sighting media read"
  on public.wildlife_sighting_media for select to authenticated
  using (
    public.is_editor()
    or auth.uid() = user_id
    or exists (
      select 1 from public.wildlife_sightings s
      where s.id = wildlife_sighting_media.sighting_id
        and s.status = 'published' and s.is_published = true)
  );

drop policy if exists "owners insert sighting media" on public.wildlife_sighting_media;
create policy "owners insert sighting media"
  on public.wildlife_sighting_media for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "owners update sighting media" on public.wildlife_sighting_media;
create policy "owners update sighting media"
  on public.wildlife_sighting_media for update to authenticated
  using (auth.uid() = user_id or public.is_editor())
  with check (auth.uid() = user_id or public.is_editor());

drop policy if exists "owners delete sighting media" on public.wildlife_sighting_media;
create policy "owners delete sighting media"
  on public.wildlife_sighting_media for delete to authenticated
  using (auth.uid() = user_id or public.is_editor());

alter table public.wildlife_sighting_audit_log enable row level security;

-- Audit log is append-only from the database itself: SELECT for editors only,
-- and deliberately no INSERT/UPDATE/DELETE policy for any client role.
drop policy if exists "editors read sighting audit log" on public.wildlife_sighting_audit_log;
create policy "editors read sighting audit log"
  on public.wildlife_sighting_audit_log for select to authenticated
  using (public.is_editor());

alter table public.sighting_notifications enable row level security;

drop policy if exists "owners read own sighting notifications" on public.sighting_notifications;
create policy "owners read own sighting notifications"
  on public.sighting_notifications for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "owners update own sighting notifications" on public.sighting_notifications;
create policy "owners update own sighting notifications"
  on public.sighting_notifications for update to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "owners delete own sighting notifications" on public.sighting_notifications;
create policy "owners delete own sighting notifications"
  on public.sighting_notifications for delete to authenticated
  using (auth.uid() = user_id);

alter table public.wildlife_contributor_profiles enable row level security;

drop policy if exists "owners manage own contributor profile" on public.wildlife_contributor_profiles;
create policy "owners manage own contributor profile"
  on public.wildlife_contributor_profiles for all to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "editors read contributor profiles" on public.wildlife_contributor_profiles;
create policy "editors read contributor profiles"
  on public.wildlife_contributor_profiles for select to authenticated
  using (public.is_editor());

-- -----------------------------------------------------------------------------
-- 8. PUBLIC PROJECTIONS (definer views owned by the migration role)
-- These are the ONLY surfaces public/anon clients can read, and they contain
-- no coordinates, no user ids and no editorial/private notes. Precise
-- coordinates are therefore structurally unexposed.
-- -----------------------------------------------------------------------------

create or replace view public.public_wildlife_sightings as
select
  s.id,
  s.common_name,
  s.bengali_name,
  s.scientific_name,
  s.description,
  s.observed_at,
  s.observed_time,
  s.habitat,
  s.individual_count,
  s.behaviour,
  s.iucn_status,
  s.district,
  s.state,
  s.country,
  s.public_location_label,
  s.public_location_precision,
  s.sensitivity_level,
  s.verification_status,
  s.featured,
  s.editorial_priority,
  s.published_at,
  s.created_at,
  case
    when s.contributor_privacy = 'named'
      then coalesce(nullif(btrim(coalesce(s.contributor_display_name, '')), ''),
                    'নাগরিক বিজ্ঞানী')
    else null
  end as contributor_name,
  (s.contributor_privacy = 'named') as contributor_public
from public.wildlife_sightings s
where s.status = 'published' and s.is_published = true;

comment on view public.public_wildlife_sightings is
  'Masked public projection of published sightings. Deliberately excludes latitude/longitude, user_id and editorial notes.';

create or replace view public.public_sighting_media as
select
  m.id,
  m.sighting_id,
  m.media_type,
  m.bucket_id,
  m.storage_path,
  m.mime_type,
  m.caption,
  m.display_order,
  m.created_at
from public.wildlife_sighting_media m
join public.wildlife_sightings s on s.id = m.sighting_id
where s.status = 'published' and s.is_published = true;

create or replace view public.public_contributors as
select
  p.user_id,
  p.display_name,
  p.district,
  p.state,
  p.bio_bn,
  p.created_at
from public.wildlife_contributor_profiles p
where p.privacy = 'named'
  and nullif(btrim(coalesce(p.display_name, '')), '') is not null;

create or replace view public.public_contributor_stats as
select
  s.user_id,
  count(*) filter (where s.status <> 'draft') as submitted,
  count(*) filter (where s.status = 'published') as published,
  count(*) filter (where s.verification_status in ('editor_verified', 'scientifically_verified')) as verified
from public.wildlife_sightings s
join public.wildlife_contributor_profiles p
  on p.user_id = s.user_id and p.privacy = 'named'
where s.user_id is not null and s.status <> 'rejected'
group by s.user_id;

grant select on public.public_wildlife_sightings to anon, authenticated;
grant select on public.public_sighting_media to anon, authenticated;
grant select on public.public_contributors to anon, authenticated;
grant select on public.public_contributor_stats to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 9. RPCs
-- -----------------------------------------------------------------------------

-- Editorial KPI counters for the Citizen Science module.
create or replace function public.citizen_science_stats()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_result jsonb;
begin
  if not public.is_editor() then
    raise exception 'editor access required';
  end if;

  select jsonb_build_object(
    'total', count(*),
    'pending_review', count(*) filter (where status in ('submitted', 'under_review')),
    'today', count(*) filter (where submitted_at >= date_trunc('day', now())),
    'published', count(*) filter (where status = 'published'),
    'flagged', count(*) filter (where is_flagged),
    'needs_information', count(*) filter (where status = 'needs_information'),
    'approved', count(*) filter (where status = 'approved'),
    'featured', count(*) filter (where featured and status = 'published')
  )
  into v_result
  from public.wildlife_sightings;

  return v_result;
end;
$$;

-- Contributor reputation metrics (no competitive ranking — Phase 6 owns that).
create or replace function public.my_sighting_stats()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'submitted', count(*) filter (where status <> 'draft'),
    'published', count(*) filter (where status = 'published'),
    'verified', count(*) filter (
      where verification_status in ('editor_verified', 'scientifically_verified')),
    'pending', count(*) filter (where status in ('submitted', 'under_review')),
    'needs_information', count(*) filter (where status = 'needs_information')
  )
  from public.wildlife_sightings
  where user_id = auth.uid();
$$;

-- Soft duplicate detection used by the submission form to warn (never block).
create or replace function public.check_sighting_duplicate(
  p_common_name text,
  p_observed_at date,
  p_district text default null
)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'sighting_id', s.id,
        'status', s.status,
        'observed_at', s.observed_at,
        'common_name', s.common_name)
      from public.wildlife_sightings s
      where s.user_id = auth.uid()
        and s.status <> 'rejected'
        and s.observed_at = coalesce(p_observed_at, current_date)
        and lower(btrim(coalesce(s.common_name, ''))) = lower(btrim(coalesce(p_common_name, '')))
        and (p_district is null
             or lower(btrim(coalesce(s.district, ''))) = lower(btrim(coalesce(p_district, ''))))
      order by s.created_at desc
      limit 1
    ),
    'null'::jsonb);
$$;

-- Any authenticated reader can flag published content for moderation review.
-- Runs as definer so a reader never needs UPDATE rights on the sighting row.
create or replace function public.report_sighting(p_sighting_id uuid, p_reason text default null)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_reason text := left(coalesce(nullif(btrim(coalesce(p_reason, '')), ''),
                                 'ব্যবহারকারীর রিপোর্ট'), 500);
begin
  if auth.uid() is null then
    raise exception 'লগইন আবশ্যক / Authentication required';
  end if;

  if not exists (
    select 1 from public.wildlife_sightings s
    where s.id = p_sighting_id and s.status = 'published' and s.is_published = true) then
    raise exception 'দর্শনটি পাওয়া যায়নি / Sighting not available';
  end if;

  perform set_config('earanyak.system_write', 'on', true);

  update public.wildlife_sightings
     set is_flagged = true, flag_reason = v_reason
   where id = p_sighting_id;

  insert into public.wildlife_sighting_audit_log
    (sighting_id, actor_id, actor_role, action, details)
  values (p_sighting_id, auth.uid(), 'user', 'user_report', jsonb_build_object('reason', v_reason));

  perform set_config('earanyak.system_write', 'off', true);
end;
$$;

-- Popular species (last 90 days) for the public "জনপ্রিয় প্রজাতি" section.
create or replace function public.popular_sighting_species(p_limit integer default 12)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(jsonb_agg(row_to_json(t)), '[]'::jsonb)
  from (
    select
      coalesce(nullif(btrim(coalesce(s.bengali_name, '')), ''),
               nullif(btrim(coalesce(s.common_name, '')), '')) as species,
      max(s.common_name) as common_name,
      max(s.scientific_name) as scientific_name,
      count(*) as sighting_count
    from public.wildlife_sightings s
    where s.status = 'published' and s.is_published = true
      and s.observed_at >= (current_date - interval '90 days')
    group by 1
    order by sighting_count desc, species asc
    limit greatest(1, least(coalesce(p_limit, 12), 30))
  ) t;
$$;

grant execute on function public.citizen_science_stats() to authenticated;
grant execute on function public.my_sighting_stats() to authenticated;
grant execute on function public.check_sighting_duplicate(text, date, text) to authenticated;
grant execute on function public.report_sighting(uuid, text) to authenticated;
grant execute on function public.popular_sighting_species(integer) to anon, authenticated;
grant execute on function public.effective_sighting_precision(text, text) to anon, authenticated;
grant execute on function public.build_public_location_label(text, text, text, text, text) to anon, authenticated;

-- -----------------------------------------------------------------------------
-- 10. STORAGE — private bucket for citizen media
-- Path convention: citizen_sightings/{user_id}/{sighting_id}/{safe-filename}
-- The bucket stays private; clients only ever receive short-lived signed URLs
-- minted through ProtectedAssetService, and the SELECT policy below restricts
-- signing to the owner, editors, or media attached to a published sighting.
-- The existing wildlife_gallery / magazine_pages protection is untouched.
-- -----------------------------------------------------------------------------

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'citizen_sightings',
  'citizen_sightings',
  false,
  26214400,
  array[
    'image/jpeg', 'image/jpg', 'image/png', 'image/webp',
    'audio/mpeg', 'audio/mp3', 'audio/mp4', 'audio/wav', 'audio/x-wav', 'audio/ogg',
    'video/mp4', 'video/quicktime', 'video/webm'])
on conflict (id) do update
  set public = false,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Citizen scientists upload own sighting media" on storage.objects;
create policy "Citizen scientists upload own sighting media"
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'citizen_sightings'
    and (storage.foldername(name))[1] = auth.uid()::text
    and (storage.foldername(name))[2] ~ '^[0-9a-fA-F-]{36}$'
  );

drop policy if exists "Citizen sighting media read" on storage.objects;
create policy "Citizen sighting media read"
  on storage.objects for select to authenticated
  using (
    bucket_id = 'citizen_sightings'
    and (
      public.is_editor()
      or (storage.foldername(name))[1] = auth.uid()::text
      or exists (
        select 1 from public.wildlife_sightings s
        where s.id::text = (storage.foldername(name))[2]
          and s.status = 'published' and s.is_published = true)
    )
  );

drop policy if exists "Citizen sighting media update" on storage.objects;
create policy "Citizen sighting media update"
  on storage.objects for update to authenticated
  using (
    bucket_id = 'citizen_sightings'
    and (public.is_editor() or (storage.foldername(name))[1] = auth.uid()::text))
  with check (
    bucket_id = 'citizen_sightings'
    and (public.is_editor() or (storage.foldername(name))[1] = auth.uid()::text));

drop policy if exists "Citizen sighting media delete" on storage.objects;
create policy "Citizen sighting media delete"
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'citizen_sightings'
    and (public.is_editor() or (storage.foldername(name))[1] = auth.uid()::text));

-- -----------------------------------------------------------------------------
-- 11. SCHEMA CACHE RELOAD
-- -----------------------------------------------------------------------------
notify pgrst, 'reload schema';

commit;
