/**
 * eআরণ্যক — article image decision (server-side, single source of truth).
 *
 * STRICT PRIORITY (Phase 9 / 26):
 *
 *   SOURCE IMAGE URL -> FETCH -> VALIDATE -> USE SOURCE IMAGE
 *   only if that fails: POLLINATIONS -> stored illustration -> ARTICLE IMAGE
 *
 * Generated illustrations are NEVER preferred over a legitimate source
 * photograph. Pollinations is invoked ONLY when the source image is genuinely
 * unavailable, unfetchable or invalid (missing URL, HTTP error, HTML error
 * page, empty/corrupt body, below the existing size/safety thresholds).
 *
 * Both the news pipeline and the tutorials pipeline delegate here, so the
 * priority rule exists in exactly one place and is verifiable by tests.
 */

import { validateSourceImage } from "./source-image.ts";

export type SourceImageProvenance = "source" | "ai_generated" | "none";

export type ArticleImageOutcome = {
  /** Final image URL to store on the article row (null = none available). */
  url: string | null;
  /** "source" = original photograph, "ai_generated" = AI illustration. */
  provenance: SourceImageProvenance;
  /** Which mechanism produced the image (observability, Phase 28). */
  source: "source" | "pollinations" | "none";
  /** Why no usable image was produced (generation/storage/budget). */
  reason?: string;
  /** Why a present source image was rejected. */
  sourceImageReason?: string;
  /** Duration of the source-image validation step, ms. */
  sourceValidationMs?: number;
  /** Duration of the AI generation + storage step, ms. */
  generationMs?: number;
};

export type GeneratedImage = {
  ok: boolean;
  bytes?: Uint8Array;
  mime?: string;
  reason?: string;
};

export type StoredImageResult = {
  ok: boolean;
  publicUrl?: string | null;
  reason?: string;
};

export type ResolveArticleImageOptions = {
  /** Source image URL extracted from the article page (may be absent). */
  sourceImageUrl?: string | null;
  /** Pollinations call — invoked ONLY when no valid source image exists. */
  generate: () => Promise<GeneratedImage>;
  /** Persists generated bytes to the existing Supabase Storage bucket. */
  store: (bytes: Uint8Array, mime: string) => Promise<StoredImageResult>;
  /** Injectable for tests; defaults to the shared source-image validator. */
  validate?: (url: string) => Promise<{ ok: boolean; reason?: string }>;
  /** Remaining wall-clock budget for generation, ms. */
  budgetMs?: number;
  /** Below this remaining budget no generation is attempted (bounded work). */
  minGenerationBudgetMs?: number;
};

/**
 * Resolves the image for an article with the documented priority.
 * Never throws: every failure is reported as a structured reason so the
 * caller can continue publishing (or reject safely) without a broken URL.
 */
export async function resolveArticleImage(
  options: ResolveArticleImageOptions,
): Promise<ArticleImageOutcome> {
  const validate = options.validate ?? ((url: string) => validateSourceImage(url));
  let sourceImageReason: string | undefined;
  let sourceValidationMs: number | undefined;

  // 1) SOURCE IMAGE — strict priority.
  const sourceUrl = (options.sourceImageUrl ?? "").trim();
  if (sourceUrl) {
    const started = Date.now();
    try {
      const validation = await validate(sourceUrl);
      sourceValidationMs = Date.now() - started;
      if (validation.ok) {
        return {
          url: sourceUrl,
          provenance: "source",
          source: "source",
          sourceValidationMs,
        };
      }
      sourceImageReason = validation.reason ?? "invalid source image";
    } catch (err) {
      sourceValidationMs = Date.now() - started;
      sourceImageReason = err instanceof Error ? err.message : String(err);
    }
  } else {
    sourceImageReason = "no source image URL in article";
  }

  // 2) POLLINATIONS — only because no valid source image exists.
  const minBudget = options.minGenerationBudgetMs ?? 15000;
  const budget = options.budgetMs ?? Number.MAX_SAFE_INTEGER;
  if (budget < minBudget) {
    return {
      url: null,
      provenance: "none",
      source: "none",
      reason: `no image budget remaining (${Math.max(0, Math.round(budget))}ms < ${minBudget}ms)`,
      sourceImageReason,
      sourceValidationMs,
    };
  }

  const generationStarted = Date.now();
  try {
    const generated = await options.generate();
    if (!generated.ok || !generated.bytes || !generated.mime) {
      return {
        url: null,
        provenance: "none",
        source: "none",
        reason: `generation failed: ${generated.reason ?? "unknown"}`,
        sourceImageReason,
        sourceValidationMs,
        generationMs: Date.now() - generationStarted,
      };
    }
    const stored = await options.store(generated.bytes, generated.mime);
    if (!stored.ok || !stored.publicUrl) {
      return {
        url: null,
        provenance: "none",
        source: "none",
        reason: `storage failed: ${stored.reason ?? "unknown"}`,
        sourceImageReason,
        sourceValidationMs,
        generationMs: Date.now() - generationStarted,
      };
    }
    return {
      url: stored.publicUrl,
      provenance: "ai_generated",
      source: "pollinations",
      sourceImageReason,
      sourceValidationMs,
      generationMs: Date.now() - generationStarted,
    };
  } catch (err) {
    return {
      url: null,
      provenance: "none",
      source: "none",
      reason: `generation error: ${err instanceof Error ? err.message : String(err)}`,
      sourceImageReason,
      sourceValidationMs,
      generationMs: Date.now() - generationStarted,
    };
  }
}